import { createFileRoute, Link } from "@tanstack/react-router";
import { Barcode, Search, ShieldCheck, Sparkles, ArrowRight } from "lucide-react";
import { Logo } from "@/components/Logo";
import { Button } from "@/components/ui/button";
import { ScanIllustration } from "@/components/ScanIllustration";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "SentraAI — Smart Product Analysis Powered by AI" },
      {
        name: "description",
        content:
          "Scan, search, and understand products instantly with intelligent insights from the SentraAI analysis engine.",
      },
      { property: "og:title", content: "SentraAI — Smart Product Analysis Powered by AI" },
      {
        property: "og:description",
        content: "Scan, search, and understand products instantly with intelligent insights.",
      },
    ],
  }),
  component: Landing,
});

const features = [
  {
    icon: Search,
    title: "Product Search",
    text: "Find any product by name, brand or category across a growing index.",
  },
  {
    icon: Barcode,
    title: "Barcode Scanning",
    text: "Point, scan and identify packaged goods in under two seconds.",
  },
  {
    icon: Sparkles,
    title: "AI Analysis",
    text: "Ingredient, safety and quality insights generated by our AI engine.",
  },
  {
    icon: ShieldCheck,
    title: "Secure User Access",
    text: "Protected accounts with validated sign-up and session handling.",
  },
];

function Landing() {
  return (
    <div className="aurora relative min-h-screen overflow-hidden">
      <div className="pointer-events-none absolute -left-32 top-40 h-96 w-96 rounded-full bg-accent/15 blur-[140px]" />
      <div className="pointer-events-none absolute -right-32 top-0 h-96 w-96 rounded-full bg-primary/15 blur-[140px]" />

      <header className="relative z-10 mx-auto flex max-w-6xl items-center justify-between px-4 py-5 sm:px-6">
        <Logo />
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" asChild>
            <Link to="/login">Login</Link>
          </Button>
          <Button variant="hero" size="sm" asChild>
            <Link to="/register">Get Started</Link>
          </Button>
        </div>
      </header>

      <main className="relative z-10 mx-auto max-w-6xl px-4 sm:px-6">
        <section className="grid items-center gap-12 py-12 lg:grid-cols-2 lg:py-20">
          <div className="animate-rise">
            <span className="inline-flex items-center gap-2 rounded-full border border-border bg-secondary/40 px-3 py-1 text-xs text-muted-foreground">
              <span className="h-1.5 w-1.5 rounded-full bg-primary" />
              Module 1 · Auth &amp; Product Scanning
            </span>
            <h1 className="mt-5 text-4xl font-bold leading-[1.08] sm:text-5xl lg:text-6xl">
              Smart Product Analysis <span className="text-gradient">Powered by AI</span>
            </h1>
            <p className="mt-5 max-w-lg text-base text-muted-foreground sm:text-lg">
              Scan, search, and understand products instantly with intelligent insights.
            </p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <Button variant="hero" size="lg" asChild>
                <Link to="/register">
                  Get Started <ArrowRight />
                </Link>
              </Button>
              <Button variant="glass" size="lg" asChild>
                <Link to="/login">Login</Link>
              </Button>
            </div>
            <dl className="mt-10 grid max-w-md grid-cols-3 gap-4">
              {[
                ["2.1s", "Avg. analysis"],
                ["98.4%", "Match accuracy"],
                ["24/7", "Always on"],
              ].map(([v, l]) => (
                <div key={l}>
                  <dt className="font-display text-2xl font-bold text-primary">{v}</dt>
                  <dd className="text-xs text-muted-foreground">{l}</dd>
                </div>
              ))}
            </dl>
          </div>

          <div className="flex justify-center lg:justify-end">
            <ScanIllustration />
          </div>
        </section>

        <section className="pb-20">
          <h2 className="text-2xl font-bold sm:text-3xl">Everything the scanner needs</h2>
          <p className="mt-2 max-w-xl text-sm text-muted-foreground">
            A focused toolkit that turns a product name, barcode or photo into structured
            intelligence.
          </p>

          <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {features.map((f, i) => (
              <div
                key={f.title}
                style={{ animationDelay: `${i * 80}ms` }}
                className="glass animate-rise group rounded-3xl p-5 transition-all duration-300 hover:-translate-y-1 hover:border-primary/40"
              >
                <span className="grid h-11 w-11 place-items-center rounded-2xl bg-secondary/60 text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground">
                  <f.icon className="h-5 w-5" />
                </span>
                <h3 className="mt-4 text-base font-semibold">{f.title}</h3>
                <p className="mt-1.5 text-sm text-muted-foreground">{f.text}</p>
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer className="relative z-10 border-t border-border py-6 text-center text-xs text-muted-foreground">
        © {new Date().getFullYear()} SentraAI · Intelligent product analysis
      </footer>
    </div>
  );
}
